
vec = ['ARGCRO', 'ARGISL', 'AUSPER', 'BELENG', 'BELJPN', 'BELPAN', 'BELTUN', 'BRABEL', 'BRACRC', 'BRAMEX', 'BRASUI',
       'COLENG', 'COLJPN', 'CRCSRB', 'CRODEN', 'CROENG', 'DENAUS', 'DENFRA', 'EGYURU', 'ENGBEL', 'ESPMAR', 'ESPRUS',
       'FRAARG', 'FRAAUS', 'FRABEL', 'FRACRO', 'FRAPER', 'GERMEX', 'GERSWE', 'IRNESP', 'IRNPOR', 'ISLCRO', 'JPNPOL',
       'KORGER', 'KORMEX', 'KSAEGY', 'MARIRN', 'MEXSWE', 'NGAARG', 'NGAISL', 'PANTUN', 'PERDEN', 'POLSEN', 'PORESP',
       'PORMAR', 'RUSCRO', 'RUSEGY', 'RUSKSA', 'SENCOL', 'SERBRA', 'SRBBRA', 'SRBSUI', 'SUICRC', 'SWEENG', 'SWEKOR',
       'SWESUI', 'TUNENG', 'URUFRA', 'URUKSA', 'URUPOR', 'URURUS', 'worldcuprussia2018']




